import "server-only";
import type { Offer } from "@/domain/catalog";
// Entirely fictional examples; not current offers or real merchant listings.
export const demoOffers: readonly Offer[] = [
  {
    id: "demo-1",
    slug: "fone-sem-fio",
    title: "Fone sem fio com cancelamento de ruído",
    description:
      "Uma pausa no barulho. Som envolvente e conforto para acompanhar seu dia.",
    category: "tecnologia",
    priceCents: 24990,
    referencePriceCents: 39990,
    status: "published",
    art: "headphones",
    color: "lavender",
    featured: true,
  },
  {
    id: "demo-2",
    slug: "cafeteira-compacta",
    title: "Cafeteira elétrica compacta 600 ml",
    description:
      "Seu café, no seu ritmo. Uma companhia para as primeiras horas da manhã.",
    category: "cozinha",
    priceCents: 13990,
    referencePriceCents: 19990,
    status: "published",
    art: "coffee",
    color: "peach",
    featured: false,
  },
  {
    id: "demo-3",
    slug: "teclado-mecanico",
    title: "Teclado mecânico compacto sem fio",
    description:
      "Mais espaço na mesa e conforto para criar, estudar e trabalhar.",
    category: "tecnologia",
    priceCents: 18990,
    referencePriceCents: 28990,
    status: "published",
    art: "keyboard",
    color: "mint",
    featured: false,
  },
  {
    id: "demo-4",
    slug: "luminaria-de-mesa",
    title: "Luminária de mesa com luz ajustável",
    description:
      "A iluminação certa para o seu cantinho. Um toque de aconchego na rotina.",
    category: "casa",
    priceCents: 7990,
    referencePriceCents: 11990,
    status: "published",
    art: "lamp",
    color: "sand",
    featured: false,
  },
  {
    id: "demo-5",
    slug: "caixa-de-som",
    title: "Caixa de som portátil Bluetooth",
    description:
      "Leve suas músicas favoritas para perto. Compacta e fácil de transportar.",
    category: "tecnologia",
    priceCents: 15990,
    referencePriceCents: 21990,
    status: "published",
    art: "speaker",
    color: "blue",
    featured: false,
  },
  {
    id: "demo-6",
    slug: "garrafa-termica",
    title: "Garrafa térmica em inox 750 ml",
    description:
      "Uma boa companhia entre um compromisso e outro. Praticidade para o dia todo.",
    category: "bem-estar",
    priceCents: 6990,
    referencePriceCents: 9990,
    status: "published",
    art: "bottle",
    color: "rose",
    featured: false,
  },
  {
    id: "demo-7",
    slug: "fone-em-revisao",
    title: "Fone de ouvido em revisão",
    description: "Exemplo de rascunho ainda não disponível no catálogo.",
    category: "tecnologia",
    priceCents: 19990,
    referencePriceCents: 29990,
    status: "draft",
    art: "headphones",
    color: "sand",
    featured: false,
  },
  {
    id: "demo-8",
    slug: "luminaria-encerrada",
    title: "Luminária — exemplo encerrado",
    description: "Exemplo de promoção que deixou de estar disponível.",
    category: "casa",
    priceCents: 5990,
    referencePriceCents: 9990,
    status: "expired",
    art: "lamp",
    color: "mint",
    featured: false,
  },
];
